Добавил 2 функции
htmlacademy-javascript/1801871-keksobooking-23 pull request #2
Opened 2021-06-02 12:08 UTC by ViktorBelenov

Добавил 2 функции

2021-06-02 22:10 UTC, copperkraft requested changes
По всем вопросам пиши мне в телеграм или вк, ссылки можешь найти в описании аккаунта htmlacademy.

2021-06-02 22:10 UTC, copperkraft commented on js/main.js
> +  if (max-min<1 || min<0){ //max-min<1 проверка того, чтобы хотя бы одно целое число было в диапозоне//
От 2.9 до 3.1 есть целое число, но его не угадывает. 
Также хотелось бы, чтобы (1, 2) выдавало поровну 1 и 2, а не только 1. 
На мой вкус я бы ставил больше пробелов. 
`(max - min < 1 || min < 0)`, но это, возможно, будет проверяться потом через eslint.

2021-06-02 22:10 UTC, copperkraft commented on js/main.js
> +  const Random = min + Math.random()*(max-min);
Стоит придерживаться правил наименования переменных. В данном случае пишется со строчной буквы. Также лучше добавлять в название переменных существительные. 
Кроме того, можно возвращать значение напрямую из функции, без заведения дополнительной переменной. 
Подробнее с критериями проверки можно ознакомиться по ссылке: https://up.htmlacademy.ru/javascript/23/criteries

2021-06-02 22:10 UTC, copperkraft commented on js/main.js
> +    return 'Ошибка диапазона';
Я бы отошел от практики простого возвращения строки в случае неправильных данных. Я бы в целом постарался сделать функцию так, чтобы она не ломалась вне зависимости от входных параметров, за исключением случаев, когда между двумя числами действительно нет ни одного целого.

2021-06-02 22:10 UTC, copperkraft commented on js/main.js
> +    return 'Ошибка диапазона';
Если хочется обработать "ошибочную" ситуацию, лучше использовать `Error`, про обработку ошибок можешь почитать отдельно.

2021-06-02 22:10 UTC, copperkraft commented on js/main.js
> +  if (min>=max || min<0 ){
Кстати, чтобы не повторялась логика в двух функциях, ты можешь использовать в первой вторую или наоборот.

2021-06-03 08:56 UTC, ViktorBelenov commented on js/main.js
> +  if (min>=max || min<0 ){
То есть обернуть условие if в функцию которая выдает true или false и подставлять в условие?

2021-06-03 18:39 UTC, merged